var OAUTH2_CLIENT_ID="147378973529.apps.googleusercontent.com";var OAUTH2_SCOPES=["https://www.googleapis.com/auth/youtube"];var googleApiClientReady=function(){var v3=true;if(v3)gapi.client.load("youtube","v3",function(){gapi.client.setApiKey("AIzaSyCGcCoNxZOFFX67nQACx-aXGsu8u3lUBPg")});else gapi.auth.init(function(){window.setTimeout(function(){gapi.auth.authorize({client_id:OAUTH2_CLIENT_ID,scope:OAUTH2_SCOPES,immediate:true},handleAuthResult)},1)})};
function handleAuthResult(authResult){console.log("'authResult'?: "+(authResult?"TRUE":"FALSE"));if(authResult){$(".pre-auth").hide();gapi.client.load("youtube","v3",function(){function getHistory(){$.getJSON("https://gdata.youtube.com/feeds/api/users/default/watch_history"+"?v=2"+"&alt=json"+"&start-index="+(entries.length+1)+"&max-results=50"+"&access_token="+authResult.access_token,function(data){console.log(entries);$("#youtube-results").html(entries.join(",,,"));if(data.feed.entry.length==0)return;
console.log(data);$.each(data.feed.entry,function(ix,entry){entries.push(entry.title.$t+"::::"+entry.updated.$t)});getHistory()})}var entries=[];getHistory();console.log("Issued query ...")})}else $("#login-link").click(function(){gapi.auth.authorize({client_id:OAUTH2_CLIENT_ID,scope:OAUTH2_SCOPES,immediate:false},handleAuthResult)})}function loadAPIClientInterfaces(){gapi.client.load("youtube","v3",function(){handleAPILoaded()})}
(function(e){var t=function(){var e="s",n=function(e){var t=-e.getTimezoneOffset();return t!==null?t:0},r=function(e,t,n){var r=new Date;return e!==undefined&&r.setFullYear(e),r.setDate(n),r.setMonth(t),r},i=function(e){return n(r(e,0,2))},s=function(e){return n(r(e,5,2))},o=function(e){var t=e.getMonth()>7?s(e.getFullYear()):i(e.getFullYear()),r=n(e);return t-r!==0},u=function(){var t=i(),n=s(),r=i()-s();return r<0?t+",1":r>0?n+",1,"+e:t+",0"},a=function(){var e=u();return new t.TimeZone(t.olson.timezones[e])},
f=function(e){var t=new Date(2010,6,15,1,0,0,0),n={"America/Denver":new Date(2011,2,13,3,0,0,0),"America/Mazatlan":new Date(2011,3,3,3,0,0,0),"America/Chicago":new Date(2011,2,13,3,0,0,0),"America/Mexico_City":new Date(2011,3,3,3,0,0,0),"America/Asuncion":new Date(2012,9,7,3,0,0,0),"America/Santiago":new Date(2012,9,3,3,0,0,0),"America/Campo_Grande":new Date(2012,9,21,5,0,0,0),"America/Montevideo":new Date(2011,9,2,3,0,0,0),"America/Sao_Paulo":new Date(2011,9,16,5,0,0,0),"America/Los_Angeles":new Date(2011,
2,13,8,0,0,0),"America/Santa_Isabel":new Date(2011,3,5,8,0,0,0),"America/Havana":new Date(2012,2,10,2,0,0,0),"America/New_York":new Date(2012,2,10,7,0,0,0),"Asia/Beirut":new Date(2011,2,27,1,0,0,0),"Europe/Helsinki":new Date(2011,2,27,4,0,0,0),"Europe/Istanbul":new Date(2011,2,28,5,0,0,0),"Asia/Damascus":new Date(2011,3,1,2,0,0,0),"Asia/Jerusalem":new Date(2011,3,1,6,0,0,0),"Asia/Gaza":new Date(2009,2,28,0,30,0,0),"Africa/Cairo":new Date(2009,3,25,0,30,0,0),"Pacific/Auckland":new Date(2011,8,26,7,
0,0,0),"Pacific/Fiji":new Date(2010,11,29,23,0,0,0),"America/Halifax":new Date(2011,2,13,6,0,0,0),"America/Goose_Bay":new Date(2011,2,13,2,1,0,0),"America/Miquelon":new Date(2011,2,13,5,0,0,0),"America/Godthab":new Date(2011,2,27,1,0,0,0),"Europe/Moscow":t,"Asia/Yekaterinburg":t,"Asia/Omsk":t,"Asia/Krasnoyarsk":t,"Asia/Irkutsk":t,"Asia/Yakutsk":t,"Asia/Vladivostok":t,"Asia/Kamchatka":t,"Europe/Minsk":t,"Australia/Perth":new Date(2008,10,1,1,0,0,0)};return n[e]};return{determine:a,date_is_dst:o,dst_start_for:f}}();
t.TimeZone=function(e){var n={"America/Denver":["America/Denver","America/Mazatlan"],"America/Chicago":["America/Chicago","America/Mexico_City"],"America/Santiago":["America/Santiago","America/Asuncion","America/Campo_Grande"],"America/Montevideo":["America/Montevideo","America/Sao_Paulo"],"Asia/Beirut":["Asia/Beirut","Europe/Helsinki","Europe/Istanbul","Asia/Damascus","Asia/Jerusalem","Asia/Gaza"],"Pacific/Auckland":["Pacific/Auckland","Pacific/Fiji"],"America/Los_Angeles":["America/Los_Angeles",
"America/Santa_Isabel"],"America/New_York":["America/Havana","America/New_York"],"America/Halifax":["America/Goose_Bay","America/Halifax"],"America/Godthab":["America/Miquelon","America/Godthab"],"Asia/Dubai":["Europe/Moscow"],"Asia/Dhaka":["Asia/Yekaterinburg"],"Asia/Jakarta":["Asia/Omsk"],"Asia/Shanghai":["Asia/Krasnoyarsk","Australia/Perth"],"Asia/Tokyo":["Asia/Irkutsk"],"Australia/Brisbane":["Asia/Yakutsk"],"Pacific/Noumea":["Asia/Vladivostok"],"Pacific/Tarawa":["Asia/Kamchatka"],"Africa/Johannesburg":["Asia/Gaza",
"Africa/Cairo"],"Asia/Baghdad":["Europe/Minsk"]},r=e,i=function(){var e=n[r],i=e.length,s=0,o=e[0];for(;s<i;s+=1){o=e[s];if(t.date_is_dst(t.dst_start_for(o))){r=o;return}}},s=function(){return typeof n[r]!="undefined"};return s()&&i(),{name:function(){return r}}},t.olson={},t.olson.timezones={"-720,0":"Etc/GMT+12","-660,0":"Pacific/Pago_Pago","-600,1":"America/Adak","-600,0":"Pacific/Honolulu","-570,0":"Pacific/Marquesas","-540,0":"Pacific/Gambier","-540,1":"America/Anchorage","-480,1":"America/Los_Angeles",
"-480,0":"Pacific/Pitcairn","-420,0":"America/Phoenix","-420,1":"America/Denver","-360,0":"America/Guatemala","-360,1":"America/Chicago","-360,1,s":"Pacific/Easter","-300,0":"America/Bogota","-300,1":"America/New_York","-270,0":"America/Caracas","-240,1":"America/Halifax","-240,0":"America/Santo_Domingo","-240,1,s":"America/Santiago","-210,1":"America/St_Johns","-180,1":"America/Godthab","-180,0":"America/Argentina/Buenos_Aires","-180,1,s":"America/Montevideo","-120,0":"Etc/GMT+2","-120,1":"Etc/GMT+2",
"-60,1":"Atlantic/Azores","-60,0":"Atlantic/Cape_Verde","0,0":"Etc/UTC","0,1":"Europe/London","60,1":"Europe/Berlin","60,0":"Africa/Lagos","60,1,s":"Africa/Windhoek","120,1":"Asia/Beirut","120,0":"Africa/Johannesburg","180,0":"Asia/Baghdad","180,1":"Europe/Moscow","210,1":"Asia/Tehran","240,0":"Asia/Dubai","240,1":"Asia/Baku","270,0":"Asia/Kabul","300,1":"Asia/Yekaterinburg","300,0":"Asia/Karachi","330,0":"Asia/Kolkata","345,0":"Asia/Kathmandu","360,0":"Asia/Dhaka","360,1":"Asia/Omsk","390,0":"Asia/Rangoon",
"420,1":"Asia/Krasnoyarsk","420,0":"Asia/Jakarta","480,0":"Asia/Shanghai","480,1":"Asia/Irkutsk","525,0":"Australia/Eucla","525,1,s":"Australia/Eucla","540,1":"Asia/Yakutsk","540,0":"Asia/Tokyo","570,0":"Australia/Darwin","570,1,s":"Australia/Adelaide","600,0":"Australia/Brisbane","600,1":"Asia/Vladivostok","600,1,s":"Australia/Sydney","630,1,s":"Australia/Lord_Howe","660,1":"Asia/Kamchatka","660,0":"Pacific/Noumea","690,0":"Pacific/Norfolk","720,1,s":"Pacific/Auckland","720,0":"Pacific/Tarawa","765,1,s":"Pacific/Chatham",
"780,0":"Pacific/Tongatapu","780,1,s":"Pacific/Apia","840,0":"Pacific/Kiritimati"},typeof exports!="undefined"?exports.jstz=t:e.jstz=t})(this);var node=typeof module!="undefined"&&module!=null;
function Limiter(obj){var _this=this,_window=1E3,_limit=3,_pending=[],_inProgress=[],_finished=[];function _ctor(){if(obj&&typeof obj=="object"){_window=obj.window||_window;_limit=obj.limit||_limit}}_this.attach=function(callback){_pending.push(callback);_launch()};function _launch(){if(_pending.length==0)return;var now=+Date.now(),nFree=_limit-_inProgress.length;for(var i=_finished.length-1;i>=0;--i){var fin=_finished[i];if(fin.finish<now-_window){_finished=_finished.slice(i+1);break}else--nFree}while(nFree>
0&&_pending.length>0){var next=_pending.shift();if(next.length==0){_finished.push({callback:next,finish:+Date.now()});next();setTimeout(function(){_launch()},_window)}else{_inProgress.push({callback:next,start:+Date.now()});next(function(){var ix=-1;for(var j=0;j<_inProgress.length;++j)if(_inProgress[j].callback==next){ix=j;break}if(ix!=-1){_inProgress.splice(ix,1);_finished.push({callback:next,finish:+Date.now()});setTimeout(function(){_launch()},_window)}})}--nFree}if(_pending.length>0)setTimeout(function(){_launch()},
_window)}_ctor()}var youtubeQueue=new Limiter({window:1E3,limit:50});if(node)module.exports=Limiter;var node=typeof module!="undefined"&&module;if(node)var $$=require("mst");function decodeEpNumber(str){var match=str.match(/^([\d\w]+)(\d{2})$/i);return{season:match[1],number:parseInt(match[2].replace(/^0+(?=\d)/g,""))}}
function Show(name,epsList){var _this=this,_seasons=[];function _ctor(){var seasonsMap={};$$.each(epsList,function(ep){ep=decodeEpEntry(ep);var season;if(!(ep.season in seasonsMap)){season=new Season(_this,ep.season);seasonsMap[ep.season]=season;_seasons.push(season)}else season=seasonsMap[ep.season];ep=new Episode(season,ep.number,ep.title)})}_this.name=function(){return name};_this.seasons=function(){return _seasons.slice()};function decodeEpEntry(str){var match=str.match(/^([\d\w]+)(\d{2})\s*\-*\s*(.*)$/i);
return{season:match[1].toUpperCase(),number:parseInt(match[2].replace(/^0+(?=\d)/g,"")),title:match[3]}}_this.nextSeason=function(season){var ix=_seasons.indexOf(season);return ix==-1||ix>=_seasons.length-1?null:_seasons[ix+1]};_this.prevSeason=function(season){var ix=_seasons.indexOf(season);return ix<=0?null:_seasons[ix-1]};_this.getSeason=function(seasonName){for(var i=0;i<_seasons.length;++i){var season=_seasons[i];if(season.name()==seasonName)return season}return null};_this.getEpisode=function(epNum){var ep=
decodeEpEntry(epNum);if(!ep)return null;var season=_this.getSeason(ep.season);return!season?null:season.getEpisode(ep.number)};_this.getAllEpisodes=function(){return $$.flatten($$.select(_seasons,function(season){return season.episodes()}))};_this.getEpRange=function(str){var match=str.match(/([k\d]\d{2,3})\-(k?\d+)/i),first=match[1],last=match[2];if(last.length<=2)last=first.substr(0,first.length-last.length)+last;var firstEp=_this.getEpisode(first),lastEp=_this.getEpisode(last);if(firstEp==null)if(lastEp==
null)return[];else return[lastEp];else if(lastEp==null)return[firstEp];else{var ret=[firstEp],next=firstEp;while((next=next.next())!=null){ret.push(next);if(next==lastEp)break}return ret}};_ctor()}
Show.get=function(){var _map={},mst3k=["K00- THE GREEN SLIME (pilot, never shown)","K01- INVADERS FROM THE DEEP","K02- REVENGE OF THE MYSTERONS","K03- STAR FORCE: FUGITIVE ALIEN 2","K04- GAMERA VS. BARUGON","K05- GAMERA","K06- GAMERA VS. GAOS","K07- GAMERA VS. ZIGRA","K08- GAMERA VS. GUIRON","K09- PHASE IV","K10- COSMIC PRINCESS","K11- HUMANOID WOMAN","K12- FUGITIVE ALIEN","K13- SST DEATH FLIGHT","K14- MIGHTY JACK","K15- SUPERDOME","K16- CITY ON FIRE","K17- TIME OF THE APES","K18- THE MILLION EYES OF SU-MURU",
"K19- HANGAR 18","K20- THE LAST CHASE","K21- LEGEND OF THE DINOSAUR","101- THE CRAWLING EYE","102- THE ROBOT VS. THE AZTEC MUMMY with short: COMMANDO CODY AND THE RADAR MEN FROM THE MOON PT 1","103- MAD MONSTER with short: COMMANDO CODY PT 2","104- WOMEN OF THE PREHISTORIC PLANET","105- THE CORPSE VANISHES with short: COMMANDO CODY PT 3","106- THE CRAWLING HAND","107- ROBOT MONSTER with shorts: COMMANDO CODY PTS 4 and 5","108- THE SLIME PEOPLE with short: COMMANDO CODY PT 6","109- PROJECT MOONBASE with shorts: COMMANDO CODY PTS 7 and 8",
"110- ROBOT HOLOCAUST with short: COMMANDO CODY PT 9 (partial)","111- MOON ZERO TWO","112- UNTAMED YOUTH","113- THE BLACK SCORPION","201- ROCKETSHIP X-M","202- THE SIDEHACKERS","203- JUNGLE GODDESS with short: THE PHANTOM CREEPS PT 1","204- CATALINA CAPER","205- ROCKET ATTACK USA with short: THE PHANTOM CREEPS PT 2","206- THE RING OF TERROR with short: THE PHANTOM CREEPS PT 3","207- WILD REBELS","208- LOST CONTINENT","209- THE HELLCATS","210- KING DINOSAUR with short: X MARKS THE SPOT","211- FIRST SPACESHIP ON VENUS",
"212- GODZILLA VS. MEGALON","213- GODZILLA VS. THE SEA MONSTER","301- CAVE DWELLERS","302- GAMERA","303- POD PEOPLE","304- GAMERA VS. BARUGON","305- STRANDED IN SPACE","306- TIME OF THE APES","307- DADDY-O with short: ALPHABET ANTICS","308- GAMERA VS. GAOS","309- THE AMAZING COLOSSAL MAN","310- FUGITIVE ALIEN","311- IT CONQUERED THE WORLD with short: SNOW THRILLS","312- GAMERA VS. GUIRON","313- EARTH VS. THE SPIDER with short: USING YOUR VOICE","314- MIGHTY JACK","315- TEENAGE CAVEMAN with shorts: AQUATIC WIZARDS and CATCHING TROUBLE",
"316- GAMERA VS. ZIGRA","317- VIKING WOMEN VS. THE SEA SERPENT with short: THE HOME ECONOMICS STORY","318- STAR FORCE - FUGITIVE ALIEN II","319- WAR OF THE COLOSSAL BEAST with short: MR. B. NATURAL","320- THE UNEARTHLY with shorts: POSTURE PALS and APPRECIATING OUR PARENTS","321- SANTA CLAUS CONQUERS THE MARTIANS","322- MASTER NINJA I","323- THE CASTLE OF FU-MANCHU","324- MASTER NINJA II","401- SPACE TRAVELERS","402- THE GIANT GILA MONSTER","403- CITY LIMITS","404- TEENAGERS FROM OUTER SPACE","405- BEING FROM ANOTHER PLANET",
"406- ATTACK OF THE GIANT LEECHES with short: UNDERSEA KINGDOM PT 1","407- THE KILLER SHREWS with short: JUNIOR RODEO DAREDEVILS","408- HERCULES UNCHAINED","409- THE INDESTRUCTIBLE MAN with short: UNDERSEA KINGDOM PT 2","410- HERCULES AGAINST THE MOON MEN","411- THE MAGIC SWORD","412- HERCULES AND THE CAPTIVE WOMEN","413- MANHUNT IN SPACE with short: GENERAL HOSPITAL PT 1","414- TORMENTED","415- THE BEATNIKS with short: GENERAL HOSPITAL PT 2","416- FIRE MAIDENS OF OUTER SPACE","417- CRASH OF THE MOONS with short: GENERAL HOSPITAL PT 3",
"418- ATTACK OF THE THE EYE CREATURES","419- THE REBEL SET with short: JOHNNY AT THE FAIR","420- THE HUMAN DUPLICATORS","421- MONSTER A-GO-GO with short: CIRCUS ON ICE","422- THE DAY THE EARTH FROZE with short: HERE COMES THE CIRCUS","423- BRIDE OF THE MONSTER with short: HIRED! PT 1",'424- "MANOS": THE HANDS OF FATE with short: HIRED! PT 2',"501- WARRIOR OF THE LOST WORLD","502- HERCULES","503- SWAMP DIAMONDS with short: WHAT TO DO ON A DATE","504- SECRET AGENT SUPER DRAGON","505- MAGIC VOYAGE OF SINBAD",
"506- EEGAH!","507- I ACCUSE MY PARENTS with short: THE TRUCK FARMER","508- OPERATION DOUBLE 007","509- GIRL IN LOVER'S LANE","510- THE PAINTED HILLS with short: BODY CARE AND GROOMING","511- GUNSLINGER","512- MITCHELL","513- THE BRAIN THAT WOULDN'T DIE","514- TEEN-AGE STRANGLER with short: IS THIS LOVE?","515- WILD, WILD WORLD OF BATWOMAN with short: CHEATING","516- ALIEN FROM L.A.","517- THE BEGINNING OF THE END","518- THE ATOMIC BRAIN with short: WHAT ABOUT JUVENILE DELINQUENCY?","519- OUTLAW (OF GOR)",
"520- RADAR SECRET SERVICE with short: LAST CLEAR CHANCE","521- SANTA CLAUS","522- TEEN-AGE CRIME WAVE","523- VILLAGE OF THE GIANTS","524- 12 TO THE MOON with short: DESIGN FOR DREAMING","601- GIRLS TOWN","602- INVASION U.S.A. with short: A DATE WITH YOUR FAMILY","603- THE DEAD TALK BACK with short: THE SELLING WIZARD","604- ZOMBIE NIGHTMARE","605- COLOSSUS AND THE HEADHUNTERS","606- THE CREEPING TERROR","607- BLOODLUST with short: UNCLE JIM'S DAIRY FARM","608- CODE NAME: DIAMOND HEAD with short: A DAY AT THE FAIR",
"609- THE SKY DIVERS with short: WHY STUDY THE INDUSTRIAL ARTS?","610- THE VIOLENT YEARS with short: YOUNG MAN'S FANCY","611- LAST OF THE WILD HORSES","612- THE STARFIGHTERS","613- THE SINISTER URGE with short: KEEPING CLEAN AND NEAT","614- SAN FRANCISCO INTERNATIONAL","615- KITTEN WITH A WHIP","616- RACKET GIRLS with short: ARE YOU READY FOR MARRIAGE?","617- THE SWORD AND THE DRAGON","618- HIGH SCHOOL BIG SHOT with short: OUT OF THIS WORLD","619- RED ZONE CUBA with short: SPEECH","620- DANGER! DEATH RAY",
"621- THE BEAST OF YUCCA FLATS with shorts: MONEY TALKS! and PROGRESS ISLAND, U.S.A.","622- ANGELS' REVENGE","623- THE AMAZING TRANSPARENT MAN with short: THE DAYS OF OUR LIVES","624- SAMSON VS. THE VAMPIRE WOMEN","701- NIGHT OF THE BLOOD BEAST with short: ONCE UPON A HONEYMOON","702- THE BRUTE MAN with short: THE CHICKEN OF TOMORROW","703- DEATHSTALKER AND THE WARRIORS FROM HELL","704- THE INCREDIBLE MELTING MAN","705- ESCAPE 2000","706- LASERBLAST","801- REVENGE OF THE CREATURE","802- THE LEECH WOMAN",
"803- THE MOLE PEOPLE","804- THE DEADLY MANTIS","805- THE THING THAT COULDN'T DIE","806- THE UNDEAD","807- TERROR FROM THE YEAR 5000","808- THE SHE CREATURE","809- I WAS A TEENAGE WEREWOLF","810- THE GIANT SPIDER INVASION",'811- "PARTS": THE CLONUS HORROR',"812- THE INCREDIBLY STRANGE CREATURES WHO STOPPED LIVING AND BECAME MIXED-UP ZOMBIES","813- JACK FROST","814- RIDING WITH DEATH","815- AGENT FOR H.A.R.M.","816- PRINCE OF SPACE","817- HORROR OF PARTY BEACH","818- DEVIL DOLL","819- INVASION OF THE NEPTUNE MEN",
"820- SPACE MUTINY","821- TIME CHASERS","822- OVERDRAWN AT THE MEMORY BANK","901- THE PROJECTED MAN","902- PHANTOM PLANET","903- PUMA MAN","904- WEREWOLF","905- THE DEADLY BEES","906- THE SPACE CHILDREN with short: CENTURY 21 CALLING","907- HOBGOBLINS","908- THE TOUCH OF SATAN","909- GORGO","910- THE FINAL SACRIFICE","911- DEVIL FISH","912- THE SCREAMING SKULL with short: ROBOT RUMPUS","913- QUEST OF THE DELTA KNIGHTS","1001- SOULTAKER","1002- THE GIRL IN GOLD BOOTS","1003- MERLIN'S SHOP OF MYSTICAL WONDERS",
"1004- FUTURE WAR","1005- BLOOD WATERS OF DR. Z","1006- BOGGY CREEK II","1007- TRACK OF THE MOON BEAST","1008- FINAL JUSTICE","1009- HAMLET","1010- IT LIVES BY NIGHT","1011- HORRORS OF SPIDER ISLAND","1012- SQUIRM with short: A CASE OF SPRING FEVER","1013- DIABOLIK"];return function(name){if(name.match(/mst3k/i)){name="mst3k";if(!(name in _map))_map[name]=new Show("MST3K",mst3k);return _map[name]}else return null}}();
function Season(show,name){var _this=this,_episodes=[];_this.name=function(){return name};_this.searchName=function(){if(name.match(/^\d+$/)){var value=parseInt(name);return(value>=10?value.toString(16):""+value).toUpperCase()}else return name};_this.episodes=function(){return _episodes};_this.nEps=function(){return _episodes.length};_this.addEpisode=function(ep){_episodes.push(ep)};_this.nextSeason=function(){return show.nextSeason(_this)};_this.prevSeason=function(){return show.prevSeason(_this)};
_this.nextEpisode=function(ep){var ix=_episodes.indexOf(ep);if(ix==-1){console.log("missing");return null}if(ix<_episodes.length-1)return _episodes[ix+1];var nextSeason=_this.nextSeason();return nextSeason==null?null:nextSeason.episodes()[0]};_this.prevEpisode=function(ep){var ix=_episodes.indexOf(ep);if(ix==-1){console.log("missing");return null}if(ix>0)return _episodes[ix-1];var prevSeason=_this.prevSeason();if(prevSeason==null)return null;var eps=prevSeason.episodes();return eps[eps.length-1]};
_this.getEpisode=function(ep){for(var i=0;i<_episodes.length;++i){var episode=_episodes[i];if(episode.number()==ep)return episode}return null};_this.toString=function(){return""+name}}Season.getEpisodes=function(seasons){return $$.flatten($$.select(seasons,function(season){return season.episodes()}))};
function Episode(season,number,title){var _this=this;function _ctor(){season.addEpisode(_this)}_this.season=function(){return season};_this.number=function(){return number};_this.title=function(){return title};_this.next=function(){return season.nextEpisode(_this)};_this.prev=function(){return season.prevEpisode(_this)};_this.toString=function(){return season.toString()+(number<10?"0":"")+number};_ctor()}if(node)module.exports={Show:Show,Season:Season,Episode:Episode};
var $$=function(){function evalKernel(kernel,key,value,obj,extras){if(kernel==null)return value;if(!(obj instanceof Array))if(extras==null)if(kernel.length==1)return kernel(value);else return kernel(key,value,obj);else{var args,nPre=0,nPost=extras.post!=null?extras.post.length:0;if(extras.pre!=null){args=extras.pre;nPre=args.length}else args=[];if(kernel.length-nPre==1)args=args.concat([value]);else args=args.concat([key,value,obj]);if(extras.post!=null)args=args.concat(extras.post);return kernel.apply(null,
args)}else if(extras==null)return kernel(value,key,obj);else{var args;if(extras.pre!=null)args=extras.pre;else args=[];args=args.concat([value,key,obj]);if(extras.post!=null)args=args.concat(extras.post);return kernel.apply(null,args)}}function each(obj,kernel){if(!(obj instanceof Array)){var count=0;for(var key in obj){if(evalKernel(kernel,key,obj[key],obj)===true)break;++count}return count}else{var style=null,start=0,len=obj.length,end=len,kernel1,arg,i=1;if(arguments.length>1){arg=arguments[i++];
if(typeof arg=="string"||typeof arg=="object"){style=arg;arg=arguments[i++];if(style=="reverse"){start=len-1;end=-1}}if(typeof arg=="number"){start=arg;if(start<0)start+=len;arg=arguments[i++]}if(typeof arg=="number"){end=arg;if(end<0)end+=len;arg=arguments[i++]}if(typeof arg=="function")kernel1=arg}if(kernel1==null)throw"Exception: 'each' called without a kernel function";if(style=="reverse")for(i=start;i>end;--i){if(i in obj&&evalKernel(kernel1,i,obj[i],obj)===true)break}else if(style==null)for(i=
start;i<end;++i){if(i in obj&&evalKernel(kernel1,i,obj[i],obj)===true)break}else throw"Exception: 'each' called with un-understood style: "+style;return i}}function select(obj,predicate){if(!(obj instanceof Array)){var ret={},item;for(var key in obj)if((item=evalKernel(predicate,key,obj[key],obj))!==undefined)if(item!=null&&typeof obj[key]!="object"&&typeof item=="object")for(var key1 in item)ret[key1]=item[key1];else ret[key]=item;return ret}else{var thisLength=obj.length,ret=[],i=1,style=null,start=
0,length=thisLength,predicate1=null,arg,end,item;if(arguments.length>1){arg=arguments[i++];if(typeof arg=="string"||typeof arg=="object"){style=arg;arg=arguments[i++];if(style=="reverse")start=length-1}if(typeof arg=="number"){start=arg;if(start<0)start+=thisLength;arg=arguments[i++];if(typeof arg=="number"){length=arg;if(length<0)length+=thisLength;arg=arguments[i++]}}if(typeof arg=="function")predicate1=arg}if(style==null){end=Math.min(thisLength,start+length);for(i=start;i<end;++i)if(i in obj&&
(item=evalKernel(predicate1,i,obj[i],obj))!==undefined)ret.push(item)}else if(style=="reverse"){end=Math.max(-1,start-length);for(i=start;i>end;--i)if(i in obj&&(item=evalKernel(predicate1,i,obj[i],obj))!==undefined)ret.push(item)}else throw"Exception: 'select' called with un-understood style: "+style;return ret}}function where(obj,predicate){if(!(obj instanceof Array)){var ret={},item;for(var key in obj)if(evalKernel(predicate,key,item=obj[key],obj)===true)ret[key]=item;return ret}else{var length=
obj.length,ret,style=null,predicate1,item,i=1,arg;if(arguments.length>1){arg=arguments[i++];if(typeof arg=="string"||typeof arg=="object"){style=arg;arg=arguments[i++]}if(typeof arg=="function")predicate1=arg}if(style=="ixes"){ret={items:[],ixes:[]};for(i=0;i<length;++i)if(i in obj&&evalKernel(predicate1,i,item=obj[i],obj)===true){ret.items.push(item);ret.ixes.push(i)}}else if(style==null){ret=[];for(i=0;i<length;++i)if(i in obj&&evalKernel(predicate1,i,item=obj[i],obj)===true)ret.push(item)}else throw"Exception: 'where' called with un-understood style: "+
style;return ret}}function sift(obj,predicate){if(!(obj instanceof Array)){var ret={},value,item,_new;for(var key in obj){item=evalKernel(predicate,key,value=obj[key],obj);if(item in ret)_new=ret[item];else ret[item]=_new={};_new[key]=value}return ret}else{var length=obj.length,style=null,predicate1,ret={},item,i=1,key,arg;if(arguments.length>1){arg=arguments[i++];if(typeof arg=="string"||typeof arg=="object"){style=arg;arg=arguments[i++]}if(typeof arg=="function")predicate1=arg}if(predicate1==null)throw"Exception: 'sift' called without a predicate";
if(style=="ixes")for(i=0;i<length;++i){if(i in obj){key=evalKernel(predicate1,i,item=obj[i],obj);if(key in ret){key=ret[key];key.items.push(item);key.ixes.push(i)}else ret[key]={items:[item],ixes:[i]}}}else for(i=0;i<length;++i)if(i in obj){key=evalKernel(predicate1,i,item=obj[i],obj);if(key in ret)ret[key].push(item);else ret[key]=[item]}return ret}}function replace(obj,kernel){if(!(obj instanceof Array)){var item;for(var key in obj)if((item=evalKernel(kernel,key,obj[key],obj))===undefined)delete obj[key];
else obj[key]=item;return obj}else{var start=0,len=obj.length,length=len,end,kernel1,item,i=1,arg;if(arguments.length>1){arg=arguments[i++];if(typeof arg=="number"){start=arg;if(start<0)start+=len;arg=arguments[i++];if(typeof arg=="number"){length=arg;arg=arguments[i++]}}if(typeof arg=="function")kernel1=arg}end=Math.min(len,start+length);for(var i=start;i<end;++i)if(i in obj)if((item=evalKernel(kernel1,i,obj[i],obj))!==undefined)obj[i]=item;else{obj.splice(i,1);--i;--len}return obj}}function toArray(obj,
kernel){var ret=[],item;for(var key in obj)if((item=evalKernel(kernel,key,obj[key],obj))!==undefined)ret.push(item);return ret}function kernel(obj,kernel1,parents){if(parents==null||!(parents instanceof Array))parents=[];var elem,ret;if(typeof obj=="object"){parents.push(obj);if(obj instanceof Array)for(var i=0;i<obj.length;++i)if((ret=kernel1(i,elem=obj[i],obj,parents))===false)continue;else{if(ret!==undefined||typeof elem=="object"&&(ret=kernel(elem,kernel1,parents))!==undefined)return ret}else for(var key in obj)if((ret=
kernel1(key,elem=obj[key],obj,parents))===false)continue;else if(ret!==undefined||typeof elem=="object"&&(ret=kernel(elem,kernel1,parents))!==undefined)return ret;parents.pop(obj)}else return kernel1(undefined,obj,undefined,parents)}function equal(obj1,obj2,strict){var isObject,isArray;if((isObject=typeof obj1=="object")^typeof obj2=="object")return false;else if(isObject)if((isArray=obj1 instanceof Array)^obj2 instanceof Array)return false;else if(isArray){var length;if((length=obj1.length)!=obj2.length)return false;
for(var i=0;i<length;++i)if(!equal(obj1[i],obj2[i],strict))return false;return true}else{for(var key in obj1)if(!(key in obj2)||!equal(obj1[key],obj2[key],strict))return false;for(var key in obj2)if(!(key in obj1))return false;return true}else return strict!==false?obj1===obj2:obj1==obj2}function clone(obj){if(obj==null)return null;else if(typeof obj=="object"){var ret;if(obj instanceof Array){ret=[];for(var i=0;i<obj.length;++i)ret.push(clone(obj[i]))}else{ret={};for(var key in obj)ret[key]=clone(obj[key])}return ret}else return obj}
function parse(str){var chars=[],charLengths={},ret=[],length=str.length,quote=null,postQuote=null,preQuoteLength=null,postQuoteLength=null,escaped=false,last=0,ix,arg,item;for(var i=1;i<arguments.length;++i)if((arg=arguments[i])instanceof Array)for(var j=0;j<arg.length;++j)chars.push(arg[j]);else chars.push(arg);if(chars.length==0){chars.push('"');chars.push("'")}console.log(chars);for(var i=0;i<chars.length;++i){item=chars[i];charLengths[item.length]=typeof item=="object"?item.pre.length:item.length}for(var i=
0;i<length;++i)if(escaped)escaped=false;else if(str.charAt(i)=="\\")escaped=true;else if(quote!=null){if(i+postQuoteLength-1<length&&str.substr(i,postQuoteLength)==postQuote){var value=str.substr(last,i+postQuoteLength-last),trimmed=value.substr(preQuoteLength,value.length-preQuoteLength-postQuoteLength);ret.push({value:value,trimmed:trimmed,delimiter:quote});quote=null;postQuote=null;preQuoteLength=null;last=i+postQuoteLength;postQuoteLength=null}}else{var lookaheads={},ix;for(var key in charLengths){var len=
charLengths[key];lookaheads[key]=i+len<=length?str.substr(i,charLengths[key]):""}for(ix=0;ix<chars.length;++ix){item=chars[ix];if((typeof item=="object"?item.pre:item)==lookaheads[item.length])break}if(ix<chars.length){if(i>last){var value=str.substr(last,i-last);ret.push({value:value,trimmed:value,delimiter:quote})}quote=chars[ix];preQuoteLength=typeof quote=="object"?quote.pre.length:quote.length;postQuote=typeof quote=="object"?quote.post:quote;postQuoteLength=postQuote.length;last=i}}if(i>last){var value=
str.substr(last,i-last);ret.push({value:value,trimmed:value,delimiter:quote})}return ret}function ix(arr){var n=arguments.length,anyArray=false,i;for(i=1;i<n;++i){var arg=arguments[i];if(arg!=null&&arg instanceof Array){anyArray=true;break}}if(anyArray){var bounds=[];for(i=1;i<n;++i){var arg=arguments[i];bounds.push(arg instanceof Array?arg.length:1)}var ret=[],control=new NdimIterator(bounds);while(control.inBounds()){var arr=ret,temp=arr;for(i=1;i<n;++i){var ix=control.ixes[i];var arg=arguments[i];
if(i<n-1){if(!(ix in arr))arr[ix]=[];arr=arr[ix];if(arg instanceof Array){ix=arg[ix];temp=temp[ix<0?temp.length+ix:ix]}else temp=temp[arg<0?temp.length+arg:arg]}else if(arg instanceof Array){var ix2=arg[ix];arr[ix]=temp[ix2<0?temp.length+ix2:ix2]}else arr[ix]=temp[arg<0?temp.length+arg:arg]}if(!control.increment())break}return ret}else{var ret=arr;for(i=1;i<n;++i){var arg=arguments[i];ret=ret[arg<0?ret.length+arg:arg]}return ret}}function singletons(obj,predicate){var ret=0,args=[null,null,obj];function recurse(arr){var length=
arr.length,n=Math.floor(args.length/2);for(var i=0;i<length;++i)if(i in arr){var item=arr[i];args[n]=i;if(item!=null&&item instanceof Array){args=args.slice(0,n+1).concat([0],args.slice(n+1),[item]);recurse(item);args=args.slice(0,n+1).concat(args.slice(n+2,-1))}else{args[0]=item;predicate.apply(null,args);++ret}}}recurse(obj);return ret}function sum(obj,predicate){if(predicate!=null)return obj.reduce(function(value,item,i){return value+predicate(item,i)},0);else return obj.reduce(function(value,
item){return value+item},0)}function prod(obj,predicate){if(predicate!=null)return obj.reduce(function(value,item,i){return value*predicate(item,i)},1);else return obj.reduce(function(value,item){return value*item},1)}function any(obj,predicate){var length=obj.length;for(var i=0;i<length;++i)if(i in obj&&evalKernel(predicate,i,obj[i],obj))return true;return false}function all(obj,predicate){var length=obj.length;for(var i=0;i<length;++i)if(i in obj&&!evalKernel(predicate,i,obj[i],obj))return false;
return true}function makeArray(obj,value){if(value===undefined)value=0;var isFunction=typeof value=="function",n=obj.length,ixes=[];function iter(i){var ret=[],length=obj[i];for(var j=0;j<length;++j){ixes[i]=j;if(i>=n-1)ret.push(isFunction?value.apply(null,ixes):value);else ret.push(iter(i+1))}return ret}return iter(0)}function colon(obj){var length=obj.length,ret=[];switch(length){case 1:var a=obj[0];for(var i=0;i<a;++i)ret.push(i);break;case 2:var a=obj[0],b=obj[1];for(var i=a;i<=b;++i)ret.push(i);
break;case 3:var a=obj[0],b=obj[1],c=obj[2];if(b<0)for(var i=a;i>=c;i+=b)ret.push(i);else for(var i=a;i<=c;i+=b)ret.push(i);break;default:throw"Exception: Bad number of elements in for colon-izing a vector";}return ret}function separate(obj,predicate){if(predicate==null)throw"Exception: 'separate' called without a predicate";var ret=[],length=obj.length,top=[];for(var i=0;i<length;++i)if(i in obj){var item=obj[i];if(evalKernel(predicate,i,obj[i],obj)){if(top.length>0){ret.push(top);top=[]}}else top.push(item)}if(top.length>
0)ret.push(top);return ret}function histo(obj,returnTuples){var obj1={},length=obj.length;for(var i=0;i<length;++i)if(i in obj){var item=obj[i];if(item in obj1)++obj1[item];else obj1[item]=1}if(returnTuples){var ret=[];for(var key in obj1)ret.push([key,obj1[key]]);return ret}else return obj1}function stats(obj,options){var length=obj.length,first=undefined,i;for(i=0;i<length;++i)if(i in obj){first=obj[i];break}if(first===undefined)return null;if(typeof first=="number"){var preStats={sum:0,sum2:0,
min:undefined,max:undefined,n:0};for(i=0;i<length;++i)if(i in obj){var item=obj[i];++preStats.n;preStats.sum+=item;preStats.sum2+=item*item;if(preStats.min===undefined||item<preStats.min)preStats.min=item;if(preStats.max===undefined||item>preStats.max)preStats.max=item}var stats1={mean:preStats.sum/preStats.n,sum:preStats.sum,count:preStats.n,min:preStats.min,max:preStats.max,stddev:Math.sqrt(preStats.sum2/preStats.n-Math.pow(preStats.sum/preStats.n,2))};if(options!=null&&typeof options=="string")for(var key in stats1)if(options.indexOf(key)==
-1)delete stats1[key];return stats1}else if(typeof first=="object"){var stats1={};for(var key in first)if(typeof first[key]=="number")stats1[key]=stats(select(obj,function(item){return item[key]}),options);return stats1}else throw"Exception: Cannot 'stats' obj array";}function shuffle(obj,style){var length=obj.length,j,temp,outShuffle;if(style==null||style=="random")for(var i=0;i<length;++i){if((j=Math.floor(Math.random()*length))!=i){temp=obj[i];obj[i]=obj[j];obj[j]=temp}}else if((outShuffle=style==
"out")||style=="in"){var len2=outShuffle?Math.floor((length+1)/2):Math.floor(length/2),i=outShuffle?1:0,repl=undefined,correct=makeArray([length],false);if(outShuffle)correct[0]=true;while(i<length)if(correct[i]){++i;repl=undefined}else{temp=obj[i];if(repl===undefined){j=outShuffle?i<len2?i*2:1+(i-len2)*2:i<len2?1+i*2:(i-len2)*2;obj[i]=obj[j]}else obj[i]=repl;correct[i]=true;j=outShuffle?i%2==0?i/2:len2+(i-1)/2:i%2==0?len2+i/2:(i-1)/2;repl=temp;i=j}}else throw"Exception: Un-understood style: '"+style+
"'";return obj}function flatten(obj){var ret=[];function kernel(vec){for(var i=0;i<vec.length;++i){var item=vec[i];if(item instanceof Array)kernel(item);else ret.push(item)}}kernel(obj);return ret}function countMat(obj,kernel){var len=obj.length;return{ix:0,ret:[],temp:[],iter:function(i){if(i<len){var radix=obj[i],bound=radix>=1?radix-1E-10:1,inc=radix>=1?1:radix,res,subRet;for(var value=0;value<=bound;value+=inc){this.temp[i]=value;if(i>=len-1){res=this.temp.slice(0);if(kernel!=null){if(kernel(res,
this.ix)===true)return}else this.ret.push(res);++this.ix}else{subRet=this.iter(i+1);if(kernel!=null&&subRet===undefined)return}}}return kernel==null?this.ret:this.ix}}.iter(0)}function subsets(obj){var length=obj.length,results=[],ms=null,kernel=null;function Helper(m){var _current=[];this.run=function(i){if(i>=length)return;_current.push(obj[i]);if(_current.length==m){var temp=_current.slice(0);if(kernel==null||(temp=kernel(temp))!==undefined)results.push(temp)}else this.run(i+1);_current.pop();
if(_current.length+(length-(i+1))<m)return;this.run(i+1)}}var i=1,arg=arguments.length>1?arguments[i]:null;if(arg!=null&&typeof arg!="function"){ms=arg;arg=arguments[++i]}else ms=colon([1,length]);if(arg!=null&&typeof arg=="function")kernel=arg;if(typeof ms=="number")(new Helper(ms)).run(0);else if(ms instanceof Array)for(var i=0;i<ms.length;++i)(new Helper(ms[i])).run(0);else throw new Error("Bad argument for 'ms': "+ms);return results}function top(obj){return obj[obj.length-1]}function ulam(ix){if(ix==
0)return{x:0,y:0};var base=Math.floor((Math.sqrt(ix)-1)/2)*2+3,pos={x:Math.floor(base/2),y:1-Math.floor(base/2)};ix-=(base-2)*(base-2);if(ix==0)return pos;var step;pos.y+=step=Math.min(base-2,ix);if((ix-=step)==0)return pos;pos.x-=step=Math.min(base-1,ix);if((ix-=step)==0)return pos;pos.y-=step=Math.min(base-1,ix);if((ix-=step)==0)return pos;pos.x+=step=Math.min(base,ix);return pos}function find(obj,kernel){var ret={value:undefined};if(!(obj instanceof Array)){ret.key=undefined;for(var key in obj)if(ret.value===
undefined||evalKernel(kernel,key,obj[key],obj,{pre:[ret.value]})){ret.value=obj[key];ret.key=key}}else{ret.key=-1;ret.ix=-1;for(var i=0;i<obj.length;++i)if(ret.value===undefined||evalKernel(kernel,i,obj[i],obj,{pre:[ret.value]})){ret.value=obj[i];ret.key=i;ret.ix=i}}return ret}function max(obj,kernel){return find(kernel!=null?select(obj,kernel):obj,function(max,item){return item>max})}function min(obj,kernel){return find(kernel!=null?select(obj,kernel):obj,function(min,item){return item<min})}function sort(obj){var args=
arguments;if(args.length==1)obj.sort();else obj.sort(function(a,b){for(var i=1;i<args.length;++i){var temp=args[i](a,b);if(temp!=0)return temp}return 0});return obj}function sortIxes(obj){var args=arguments,tempArr=select(obj,function(value,ix){return{value:value,ix:ix}});if(args.length==1)tempArr.sort(function(a,b){return a.value<b.value?-1:a.value>b.value?1:0});else tempArr.sort(function(a,b){for(var i=1;i<args.length;++i){var temp=args[i](a.value,b.value);if(temp!=0)return temp}return 0});return{array:select(tempArr,
function(item){return item.value}),ixes:select(tempArr,function(item){return item.ix})}}function pretty(config){var configObj,value=(configObj=typeof config=="object")?config.value:config;if(typeof value=="number"){var integerSep=",",decimalSep=" ",group=3;if(configObj){integerSep=config.integerSep||config.separator||integerSep;decimalSep=config.decimalSep||integerSep;group=config.group||group}var neg=value<0;value=value.toString();var ints=value.match(/^-?(\d+)/),decs=value.match(/\.(\d+)$/);if(ints!=
null){var str=ints[1],vals=[];for(var i=str.length-group;i>=0;i-=group)vals.push(str.substr(i,group));if(i>-group)vals.push(str.substr(0,i+group));vals.reverse();ints=vals.join(integerSep)}if(decs!=null){var str=decs[1],vals=[];for(var i=0;i<str.length;i+=group)vals.push(str.substring(i,Math.min(i+group,str.length)));decs=vals.join(decimalSep)}return(neg?"-":"")+(ints||"0")+(decs!=null?"."+decs:"")}else throw new Error("Don't know how to prettify: "+config);}return{evalKernel:evalKernel,each:each,
select:select,where:where,sift:sift,replace:replace,toArray:toArray,kernel:kernel,equal:equal,clone:clone,parse:parse,ix:ix,singletons:singletons,sum:sum,prod:prod,any:any,all:all,makeArray:makeArray,colon:colon,separate:separate,histo:histo,stats:stats,shuffle:shuffle,flatten:flatten,countMat:countMat,subsets:subsets,top:top,ulam:ulam,find:find,max:max,min:min,sort:sort,sortIxes:sortIxes,pretty:pretty}}();var node=typeof module!="undefined"&&module;if(node)var $$=require("mst");
var engColors={"aliceblue":"#F0F8FF","antiquewhite":"#FAEBD7","aqua":"#00FFFF","aquamarine":"#7FFFD4","azure":"#F0FFFF","beige":"#F5F5DC","bisque":"#FFE4C4","black":"#000000","blanchedalmond":"#FFEBCD","blue":"#0000FF","blueviolet":"#8A2BE2","brown":"#A52A2A","burlywood":"#DEB887","cadetblue":"#5F9EA0","chartreuse":"#7FFF00","chocolate":"#D2691E","coral":"#FF7F50","cornflowerblue":"#6495ED","cornsilk":"#FFF8DC","crimson":"#DC143C","cyan":"#00FFFF","darkblue":"#00008B","darkcyan":"#008B8B","darkgoldenrod":"#B8860B",
"darkgray":"#A9A9A9","darkgrey":"#A9A9A9","darkgreen":"#006400","darkkhaki":"#BDB76B","darkmagenta":"#8B008B","darkolivegreen":"#556B2F","darkorange":"#FF8C00","darkorchid":"#9932CC","darkred":"#8B0000","darksalmon":"#E9967A","darkseagreen":"#8FBC8F","darkslateblue":"#483D8B","darkslategray":"#2F4F4F","darkslategrey":"#2F4F4F","darkturquoise":"#00CED1","darkviolet":"#9400D3","deeppink":"#FF1493","deepskyblue":"#00BFFF","dimgray":"#696969","dimgrey":"#696969","dodgerblue":"#1E90FF","firebrick":"#B22222",
"floralwhite":"#FFFAF0","forestgreen":"#228B22","fuchsia":"#FF00FF","gainsboro":"#DCDCDC","ghostwhite":"#F8F8FF","gold":"#FFD700","goldenrod":"#DAA520","gray":"#808080","grey":"#808080","green":"#008000","greenyellow":"#ADFF2F","honeydew":"#F0FFF0","hotpink":"#FF69B4","indianred":"#CD5C5C","indigo":"#4B0082","ivory":"#FFFFF0","khaki":"#F0E68C","lavender":"#E6E6FA","lavenderblush":"#FFF0F5","lawngreen":"#7CFC00","lemonchiffon":"#FFFACD","lightblue":"#ADD8E6","lightcoral":"#F08080","lightcyan":"#E0FFFF",
"lightgoldenrodyellow":"#FAFAD2","lightgray":"#D3D3D3","lightgrey":"#D3D3D3","lightgreen":"#90EE90","lightpink":"#FFB6C1","lightsalmon":"#FFA07A","lightseagreen":"#20B2AA","lightskyblue":"#87CEFA","lightslategray":"#778899","lightslategrey":"#778899","lightsteelblue":"#B0C4DE","lightyellow":"#FFFFE0","lime":"#00FF00","limegreen":"#32CD32","linen":"#FAF0E6","magenta":"#FF00FF","maroon":"#800000","mediumaquamarine":"#66CDAA","mediumblue":"#0000CD","mediumorchid":"#BA55D3","mediumpurple":"#9370DB","mediumseagreen":"#3CB371",
"mediumslateblue":"#7B68EE","mediumspringgreen":"#00FA9A","mediumturquoise":"#48D1CC","mediumvioletred":"#C71585","midnightblue":"#191970","mintcream":"#F5FFFA","mistyrose":"#FFE4E1","moccasin":"#FFE4B5","navajowhite":"#FFDEAD","navy":"#000080","oldlace":"#FDF5E6","olive":"#808000","olivedrab":"#6B8E23","orange":"#FFA500","orangered":"#FF4500","orchid":"#DA70D6","palegoldenrod":"#EEE8AA","palegreen":"#98FB98","paleturquoise":"#AFEEEE","palevioletred":"#DB7093","papayawhip":"#FFEFD5","peachpuff":"#FFDAB9",
"peru":"#CD853F","pink":"#FFC0CB","plum":"#DDA0DD","powderblue":"#B0E0E6","purple":"#800080","red":"#FF0000","rosybrown":"#BC8F8F","royalblue":"#4169E1","saddlebrown":"#8B4513","salmon":"#FA8072","sandybrown":"#F4A460","seagreen":"#2E8B57","seashell":"#FFF5EE","sienna":"#A0522D","silver":"#C0C0C0","skyblue":"#87CEEB","slateblue":"#6A5ACD","slategray":"#708090","slategrey":"#708090","snow":"#FFFAFA","springgreen":"#00FF7F","steelblue":"#4682B4","tan":"#D2B48C","teal":"#008080","thistle":"#D8BFD8",
"tomato":"#FF6347","turquoise":"#40E0D0","violet":"#EE82EE","wheat":"#F5DEB3","white":"#FFFFFF","whitesmoke":"#F5F5F5","yellow":"#FFFF00","yellowgreen":"#9ACD32"};
function color2Rgb(color){if(color.toLowerCase()in engColors)color=engColors[color.toLowerCase()];var match,factor;if(color.length>=6){match=color.match(/^\#?([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i);factor=1}else{match=color.match(/^\#?([0-9a-f])([0-9a-f])([0-9a-f])$/i);factor=16}if(match==null||match.length<4)return null;else{var vals=$$.select(match.slice(1,4),function(val){return parseInt(val,16)});return{r:vals[0],g:vals[1],b:vals[2],base:256/factor}}}
function rgb2Hex(color){function value2Hex(val){val=Math.round(val).toString(16);return color.base==256&&val.length<2?"0"+val:val}return"#"+value2Hex(color.r)+value2Hex(color.g)+value2Hex(color.b)}function rgbScaleBase(rgb,base){if(rgb.base==base)return rgb;else{var factor=(base-1)/(rgb.base-1);return{r:rgb.r*factor,g:rgb.g*factor,b:rgb.b*factor,base:base}}}
function testConversions(console){$$.each(["moose","red","f00","f000","f00ff0","#f00ff0","#666","#ff8844"],function(color){var res=color2Rgb(color),str=res;if(res!=null){str="{ ";var i=0;$$.each(res,function(key,value){str+=(i++>0?", ":"")+key+": "+value})}console.log(color,"=>",str);if(res!=null)console.log(color,"=> (back)",rgb2Hex(res))})}var color="(\\\"|\\')?"+"("+"\\#?([0-9a-fA-F]{3}|[0-9a-fA-F]{6})";$$.each(engColors,function(key,value){color+="|"+key});color+=")"+"(\\\"|\\')?";
function rectifyColors(colors){$$.replace(colors,function(color){color=color.replace(/(^\s+|\s+$|'|")/g,"");if(color.indexOf("#")==-1&&color.match(/^[0-9a-fA-F]+$/i)!=null)color="#"+color;return color});return colors}
function matchColors(value){var regex=new RegExp("^\\s*\\[?\\s*"+color+"((\\,\\s*|\\s+)"+color+")*\\s*\\]?\\s*$","i"),match=value.match(regex);if(match==null)return null;var values;value=value.replace(/[^\#0-9a-zA-Z\,\s]+/g,"").replace(/(^\s+|\s+$)/g,"");if(value.indexOf(",")!=-1)values=value.split(/\s*\,\s*/);else values=value.split(/\s+/);return rectifyColors(values)}
function testMatchColors(console){$$.each(["moose","glial mice mouse","fff","#fff","#fff0","#fff000","'#fff'",'"#ffffff"',"#fff #aaa #bbb #c0c","#fff, #aaa, #bbb, #c0c","[#fff, #aaa, #bbb, #c0c]","['#fff', '#aaa', '#bbb', '#c0c']","['#fff' '#aaa' '#bbb' '#c0c']","tomato","fuchsia indianred","'fuchsia' \"indianred\"","[DimGrey, 'fuchsia', \"indianred\""],function(test){console.log(test,"=>",matchColors(test))})}
function matchColorRange(value){var regex=new RegExp("^\\s*"+color+"(\\s+to\\s+"+color+")+\\s*$","i"),match=value.match(regex);if(match==null)return null;return rectifyColors(value.split(/\s+to\s+/i))}function testMatchColorRange(console){$$.each(["red","red to blue","f00 to 00f","'#f00' to '#00f'"],function(test){console.log(test,"=>",matchColorRange(test))})}var principal=80;
function makeSwatch(color,width,height){return'<span style="width: '+width+"px; height: "+height+"px; background-color: "+color+"; "+'display: inline-block; border: 1px black solid; align: center; vertical-align: middle;">'+color+"</span>"}
function getColorsModules(){return[{name:"Colors",precedence:1,kernel:function(value){var colors=matchColors(value);if(colors==null)return false;var ret="",width=principal,height=principal;$$.each(colors,function(color,ix){ret+=makeSwatch(color,width,height)+" "});return ret}},{name:"ColorRanges",precedence:1,kernel:function(value){var colors=matchColorRange(value);if(colors==null)return false;if(colors.length==2){var ret="",width=2,height=principal,a=color2Rgb(colors[0]),b=color2Rgb(colors[1]),nSteps=
200;var maxBase=Math.max(a.base,b.base);a=rgbScaleBase(a,maxBase);b=rgbScaleBase(b,maxBase);var delta={r:(b.r-a.r)/nSteps,g:(b.g-a.g)/nSteps,b:(b.b-a.b)/nSteps};ret+=colors[0]+"&nbsp;";for(var i=0;i<=nSteps;++i){var color=rgb2Hex({r:a.r+i*delta.r,g:a.g+i*delta.g,b:a.b+i*delta.b,base:maxBase});ret+='<div style="width: '+width+"px; height: "+height+"px; background-color: "+color+"; "+'display: inline-block; padding: 0px;" '+"onmouseover=\"rangeMouseOver('"+color+"')\" "+"></div>"}ret+="&nbsp;"+colors[1]+
"<br />"+'<div id="rangeMouseOver"></div>';return ret}else return false}}]}function rangeMouseOver(color){$("#rangeMouseOver").html(makeSwatch(color,principal,principal))}if(node)module.exports={test:function(console){testMatchColors(console);testMatchColorRange(console);testConversions(console)}};var node=typeof module!="undefined"&&module;if(node)var $$=require("mst");function isPrime(n){if(n<2)return false;var bound=Math.sqrt(n);for(var i=2;i<=bound;++i)if(n%i==0)return i;return true}
function matchPrimality(value){var match,number;if((match=value.match(/^\s*(is)?\s*prime\s*(\d+)\s*\??\s*$/i))!=null)number=parseInt(match[2]);else if((match=value.match(/^\s*(is)?\s*(\d+)\s*(is)?\s*prime\s*\??\s*$/i))!=null)number=parseInt(match[2]);else return false;var ret=isPrime(number);if(ret===false)return $$.pretty(number)+" is not prime.";else if(ret===true)return $$.pretty(number)+" is prime.";else if(typeof ret=="number")return $$.pretty(number)+" is not prime: "+$$.pretty(number)+" = "+
$$.pretty(ret)+" * "+$$.pretty(number/ret);else return false}function factor(number){var ret=[],div=2;while(number>1){while(number%div==0){ret.push(div);number/=div}++div;if(div*div>number){if(number>1)ret.push(number);break}}return ret}
function getNumbersModules(){return[{name:"Prime",precedence:1,kernel:matchPrimality},{name:"Factor",precedence:1,kernel:function(value){var match,number;if((match=value.match(/^\s*(please)?\s*factor\s*(\d+)\s*\,?\s*(please)?\s*$/i))!=null)number=parseInt(match[2]);else return false;if(number<1)return"Can't factor "+$$.pretty(number);else{var factors=factor(number);if(factors.length==1)return $$.pretty(number)+" is prime.";else return $$.pretty(number)+" = "+$$.select(factor(number),function(factor){return $$.pretty(factor)}).join(" * ")}}}]}
function testPrimality(console){$$.each(["glarm","is 47 prime?","is 47 PRIME?","is 47 prime","is47prime?","is prime 47?","is prime 47","is PRIME 47","isprime 47","prime 47","47 prime","47 is prime?"],function(value){console.log(value,"=>",matchPrimality(value))})}function testFactoring(console){for(var i=1;i<=1E3;++i){var factors=factor(i);if($$.any(factors,function(factor){return!isPrime(factor)}))throw new Error("Not a prime factor: "+factor);console.log(i,"=>",factors.join(","))}}
if(node)module.exports={test:function(console){testPrimality(console);testFactoring(console)}};var node=typeof module!="undefined"&&module;if(node)var $$=require("mst");
function getArrayArray(data){function getType(item){var type=typeof item;if(type=="number");else if(type instanceof Date);else if(type=="string")try{var date=new Date(item);if(date&&!isNaN(+date))type="date"}catch(e){}else throw new Error("Could not interpret type");return type}if(!(data instanceof Array)||data.length==0)return null;var ret=[],meta=[];if(data[0]instanceof Array)if($$.all(data[0],function(item){return typeof item=="string"||typeof item=="object"})){if(data.length<2)return null;ret=
data.slice();$$.replace(data[0],function(ser,six){if(typeof ser=="string")return{name:ser,type:getType(data[1][six])};else return ser})}else{$$.each(data[0],function(item,ix){meta.push({name:String.fromCharCode(65+ix),type:getType(item)})});ret=[meta].concat(data.slice())}else if(typeof data[0]=="object"){$$.each(data[0],function(key,value){meta.push({name:key,type:getType(value)})});var ret=[meta];$$.each(data,function(obj){var row=[];$$.each(meta,function(ser){row.push(obj[ser.name])});ret.push(row)})}else if(typeof data[0]==
"number"){ret=[[{name:"#",type:"string"},{name:String.fromCharCode(65),type:"number"}]];$$.each(data,function(val,ix){ret.push([""+(ix+1),val])})}else return null;$$.each(ret[0],function(ser,six){if(ser.type=="date")$$.each(ret,function(row,rix){if(rix==0)return;var item=row[six];if(!(item instanceof Date))row[six]=new Date(item)})});return ret}
function checkPlotting(value){var chart;try{chart=JSON.parse(value)}catch(e){try{chart=JSON.parse("["+value+"]")}catch(e){return false}}if(!chart)return false;else if(chart instanceof Array)chart={data:chart};else if(typeof chart=="object"){if(!chart.data||!(chart.data instanceof Array))return false}else return false;var arr=getArrayArray(chart.data);if(arr==null)return null;chart.data=arr;var xSeries={"string":-1,"date":-1,"number":-1};$$.each(chart.data[0],function(ser,six){if(xSeries[ser.type]==
-1)xSeries[ser.type]=six});var nSeries=chart.data[0].length,ixes=$$.colon([nSeries]),ix;if((ix=xSeries["string"])!=-1||(ix=xSeries["date"])!=-1||(ix=xSeries["number"])!=-1)if(ix!=0){ixes.splice(ix,1);ixes.unshift(ix)}var data=new google.visualization.DataTable;$$.each(ixes,function(ix){var ser=chart.data[0][ix];data.addColumn(ser.type,ser.name)});var matrix=[];$$.each(chart.data,function(row,rix){if(rix==0)return;var newRow=[];$$.each(ixes,function(ix){newRow.push(row[ix])});matrix.push(newRow)});
data.addRows(matrix);var options={"title":chart.title||"Plot","width":chart.width||640,"height":chart.height||480};var chart=new google.visualization.ChartWrapper({chartType:"AreaChart",dataTable:data,options:options,containerId:"results"});chart.draw();$("#results").css("width",640);return true}function getPlottingModules(){return[{name:"Plots",precedence:1,kernel:checkPlotting}]}
function testArrayArray(console){$$.each([[[1],[2],[3],[4]],[[1,"a"],[2,"5"],[3,"124"],[4,"123"]],[[1,"2011.12.31"],[2,"2012.1.1"],[3,"2012.1.2"],[4,"2012.1.3"]],[["GLARM"],[1],[2],[3],[4]],[[{name:"foo",type:"number"},{name:"bar",type:"string"}],[1,"a"],[2,"5"],[3,"124"],[4,"123"]],[["first",{name:"second",type:"date"}],[1,"2011.12.31"],[2,"2012.1.1"],[3,"2012.1.2"],[4,"2012.1.3"]],[{a:1},{a:2},{a:3},{a:4}],[{a:1,b:"a"},{a:2,b:"a6"},{a:3,b:"5"},{a:4,b:"moose"}],[{a:1,b:"2011.5.5"},{a:2,b:"2011.5.6"},
{a:3,b:"2011.5.7"},{a:4,b:"2011.5.8"}]],function(obj){console.log("^");console.log(JSON.stringify(obj,null,2));console.log("=>");var arr=getArrayArray(obj);console.log(JSON.stringify(arr,null,2));console.log("$")})}if(node)module.exports={test:function(console){testArrayArray(console)}};var node=typeof module!="undefined"&&module!=null;if(node)var $$=require("mst"),shows=require("./shows.js"),Show=shows.Show,Season=shows.Season,Episode=shows.Episode;
function assertSeasons(seasons,searchStr){return $$.where(seasons,function(season){return searchStr.indexOf(season.searchName())!=-1})}function deassertSeasons(seasons,searchStr){return $$.where(seasons,function(season){return searchStr.indexOf(season.searchName())==-1})}
function checkMstConsole(value){if(!value.match(/^mst(\s|$)/))return;var args=value.split(/\s+/),show=Show.get("MST3K"),seasons=show.seasons(),mode="random",lookups=[],searchTerm,match;for(var i=1;i<args.length;++i){var arg=args[i];if(arg.indexOf("-s=")===0){seasons=assertSeasons(seasons,arg.substr(3));mode="random"}else if(arg.indexOf("-ns=")===0){seasons=deassertSeasons(seasons,arg.substr(4));mode="random"}else if(arg.indexOf("-f=")===0){mode="find";searchTerm=arg.substr(3)}else if(arg.match(/^[k\d]\d{2,3}(,[k\d]\d{2,3})*$/i)){mode=
"lookup";lookups=lookups.concat(arg.split(/,/))}else if(arg.match(/^((k|\d{1,2})\d{2})\-(k?\d+)$/i)){mode="lookup";$$.each(show.getEpRange(arg),function(ep){lookups.push(ep.toString())})}}if(mode=="random"){var list=Season.getEpisodes(seasons),ix=Math.floor(list.length*Math.random());return"Your random "+show.name()+" episode (from season"+(_keys(seasons).length>1?"s":"")+" "+_englishJoin(_keys(seasons))+") is:<br/>\n"+list[ix]}else if(mode=="find"){var regex=new RegExp(searchTerm,"i"),list=$$.where(Season.getEpisodes(seasons),
function(item){return item.match(regex)!=null});return"Your search over '"+searchTerm+"' yielded:<br/>\n"+list.join("<br/>\n")}else if(mode=="lookup"){var str="";$$.each(lookups,function(ep){if(!(ep=show.getEpisode(ep)))return;var randID="search"+(""+Math.random()).substr(2),q=show.name().toLowerCase()+" "+ep.title().match(/^([^a-z]*)/)[0].replace(/(^\s+|\s+$)/g,"");str+=(str.length>0?"<br />\n":"")+ep.toString()+" - "+ep.title();if(node)return;console.log(q);str+='<div id="'+randID+'">Fetching YouTube links ...</div>';
youtubeQueue.attach(function(signal){var request=gapi.client.youtube.search.list({q:q,part:"snippet",maxResults:5,order:"relevance",type:"video"});request.execute(function(response){signal();var vids=[],nWaiting=0,cont=function(){vids=$$.where(vids,function(vid){return vid.data.data.duration>=3600}).slice(0,5);var vidLinks=[];$$.each(vids,function(vid){vidLinks.push('<div class="yt-video-link">'+'<a href="https://www.youtube.com/watch?v='+vid.item.id.videoId+'" title="'+vid.item.snippet.title+'">'+
'<img src="'+vid.item.snippet.thumbnails["default"].url+'"></a>'+"</img>"+"<br />"+vid.item.snippet.title+" ("+Math.round(vid.data.data.duration/60)+"m)"+"</div>")});$("#"+randID).html(vidLinks.join("")+'<div style="clear: both;"></div>')};$$.each(response.items,function(item,ix){if(item.id.videoId){++nWaiting;youtubeQueue.attach(function(signal){$.getJSON("http://gdata.youtube.com/feeds/api/videos/"+item.id.videoId+"?v=2&alt=jsonc",function(data){signal();vids.push({item:item,data:data});if(--nWaiting==
0)cont()})})}})})})});return"The "+show.name()+" episode"+(lookups.length>1?"s":"")+" you requested "+(lookups.length>1?"are":"is")+":<br />\n"+str}}function _englishJoin(arr){if(arr.length==0)return"";else if(arr.length==1)return""+arr[0];else if(arr.length==2)return arr.join(" and ");else return arr.slice(0,arr.length-1).join(", ")+", and "+arr[arr.length-1]}function getMst3kModules(){return[{name:"MST3K",precedence:1,kernel:checkMstConsole}]}
function _keys(obj){var ret=[];if(obj instanceof Array)$$.each(obj,function(elem){ret.push(elem instanceof Season?elem.name():elem)});else $$.each(obj,function(key,value){if(value!==false)ret.push(key)});return ret}
function testSeasons(console){var show=Show.get("MST3K");var seasons=show.seasons();console.log(_keys(seasons));console.log(_keys(assertSeasons(show.seasons(),"1234")));console.log(_keys(deassertSeasons(show.seasons(),"1234")));console.log(_keys(assertSeasons(show.seasons(),"A")));console.log(_keys(deassertSeasons(show.seasons(),"K")));console.log("All: "+Season.getEpisodes(seasons).length);console.log("Sans K: "+Season.getEpisodes(deassertSeasons(seasons,"K")).length);console.log("Just 10: "+Season.getEpisodes(assertSeasons(seasons,
"A")).length);console.log("Just 2,8: "+Season.getEpisodes(assertSeasons(seasons,"2,8")).length)}function testEpRange(console){var show=Show.get("MST3K");console.log(show.getEpRange("314-22"));console.log(show.getEpRange("301-05"));console.log(show.getEpRange("301-10"));console.log(show.getEpRange("309-11"));console.log(show.getEpRange("K01-19"));console.log(show.getEpRange("K00-1"));console.log(show.getEpRange("K21-103"));console.log(show.getEpRange("620-802"))}
function testQueries(console){console.log(checkMstConsole("mst 107"));console.log(checkMstConsole("mst 1009"));console.log(checkMstConsole("mst 107 1009"));console.log(checkMstConsole("mst 1008,1009,313 314,315"));console.log(checkMstConsole("mst 301-8"))}
function testEpMap(console){var show=Show.get("MST3K"),eps=show.getAllEpisodes(),epMap={};$$.each(eps,function(ep){var seasonName=ep.season().name();if(!(seasonName in epMap))epMap[seasonName]=[];epMap[seasonName].push({number:ep.toString(),title:ep.title()})});console.log(JSON.stringify(epMap));$$.each(epMap,function(key,value){console.log(key+" => "+value.length)})}
function testEpisodes(console){function print(ep){var ep1=show.getEpisode(ep);if(ep1==null)console.log("'"+ep+"' not found.");else{ep=ep1;function kernel(ep){return ep==null?"*":ep.toString()+" - "+ep.season()+"|"+ep.number()}console.log(kernel(ep.prev())+" ===> "+kernel(ep)+" ===> "+kernel(ep.next()))}}var show=Show.get("MST3K");print("K01");print("K22");print("101");print("113");print("114");print("1001");print("1013")}
if(node)module.exports={test:function(console){testEpMap(console);testSeasons(console);testQueries(console);testEpRange(console);testEpisodes(console)},Episode:Episode,Season:Season};var node=typeof module!="undefined"&&module;if(node)var $$=require("mst"),shows=require("./shows.js"),Show=shows.Show;function getMst3kVizModules(){return[{name:"MST3K-Viz",precedence:1,kernel:checkMstViz}]}
function drawCalendar(div,rows){var width=960,height=136,cellSize=17;var minYear=-1,maxYear=-1,maxViews=1;$$.each(rows,function(row){if(maxViews==-1||row.views.length>maxViews)maxViews=row.views.length;var match=row.date.match(/^\d{4}/);if(match){var gi=parseInt(match[0]);if(minYear==-1||gi<minYear)minYear=gi;if(maxYear==-1||gi>maxYear)maxYear=gi}});if(maxViews==-1)maxViews=1;if(minYear==-1)minYear=2013;if(maxYear==-1)maxYear=2014;else maxYear+=1;var day=d3.time.format("%w"),week=d3.time.format("%U"),
percent=d3.format(".1%"),format=d3.time.format("%Y-%m-%d");var color=d3.scale.quantize().domain([-maxViews,maxViews]).range(d3.range(11).map(function(d){return"q"+d+"-11"}));var monthPath=function(t0){var t1=new Date(t0.getFullYear(),t0.getMonth()+1,0),d0=+day(t0),w0=+week(t0),d1=+day(t1),w1=+week(t1);return"M"+(w0+1)*cellSize+","+d0*cellSize+"H"+w0*cellSize+"V"+7*cellSize+"H"+w1*cellSize+"V"+(d1+1)*cellSize+"H"+(w1+1)*cellSize+"V"+0+"H"+(w0+1)*cellSize+"Z"};var leRange=d3.range(minYear,maxYear);
leRange.reverse();var svg=d3.select("#"+div).selectAll("svg").data(leRange).enter().append("svg").attr("width",width).attr("height",height).attr("class","RdYlGn").append("g").attr("transform","translate("+(width-cellSize*53)/2+", "+(height-cellSize*7-1)+")");svg.append("text").attr("transform","translate(-6,"+cellSize*3.5+")rotate(-90)").style("text-anchor","middle").text(function(d){return d});var rect=svg.selectAll(".day").data(function(d){return d3.time.days(new Date(d,0,1),new Date(d+1,0,1))}).enter().append("rect").attr("class",
"day").attr("width",cellSize).attr("height",cellSize).attr("x",function(d){return week(d)*cellSize}).attr("y",function(d){return day(d)*cellSize}).datum(format);rect.append("title").text(function(d){return d});svg.selectAll(".month").data(function(d){return d3.time.months(new Date(d,0,1),new Date(d+1,0,1))}).enter().append("path").attr("class","month").attr("d",monthPath);var data=d3.nest().key(function(d){return d.date}).rollup(function(d){return d[0].views.length}).map(rows);rect.filter(function(d){return d in
data}).attr("class",function(d){return"day "+color(data[d])}).select("title").text(function(d){return d+": "+data[d]})}
function checkMstViz(value){var show=Show.get("MST3K");var pattern=/(^|\s)(([\w\d])\d{2})\s*\-?\s*((\d{4}[\.\-]\d{1,2}[\.\-]\d{1,2}(r|q|t\d*))(\s*[\,\;]\s*(\d{4}[\.\-]\d{1,2}[\.\-]\d{1,2}(r|q|t\d*)))*)/i;var rows=[],leDates={},epViews={};$$.each(show.getAllEpisodes(),function(ep){epViews[ep.toString()]={ep:ep,views:[]}});while(match=pattern.exec(value)){var number=match[2],dates=match[4],ep=show.getEpisode(number);if(ep){var subValue=match[0],datePattern=/(\d{4}[\.\-]\d{1,2}[\.\-]\d{1,2})(r|q|t\d*)/i,
subMatch;while((subMatch=datePattern.exec(subValue))!=null){var date=new Date(subMatch[1]),watchKind=subMatch[2],gi,key=date.getFullYear()+"-"+((gi=date.getMonth()+1)<10?"0"+gi:gi)+"-"+((gi=date.getDate())<10?"0"+gi:gi);epViews[ep.toString()].views.push(date);if(!(key in leDates)){leDates[key]={date:key,views:[]};rows.push(leDates[key])}leDates[key].views.push(1);subValue=subValue.substr(subMatch.index+subMatch[0].length+1)}}value=value.substr(match.index+match[0].length+1)}$$.each(epViews,function(key,
value){value.views.sort(function(a,b){return+a-+b})});if(!node)setTimeout(function(){drawCalendar("calendar",rows);var epList=$$.toArray(epViews),str=[],epKernel=function(epListElem,prefix){if(prefix===undefined||prefix=="viewCount")prefix=epListElem.views.length;else if(prefix=="mostRecent"){var views=epListElem.views;if(views.length)prefix=views[views.length-1];else prefix="N/A"}else if(prefix=="leastRecent"){var views=epListElem.views;if(views.length)prefix=views[0];else prefix="N/A"}if(typeof prefix==
"object")prefix=prefix.getFullYear()+"."+(prefix.getMonth()+1)+"."+prefix.getDate();return"<i>"+prefix+"</i> &ndash; "+epListElem.ep.toString()+" "+epListElem.ep.title()};var divWidth=250;epList.sort(function(a,b){return-(a.views.length-b.views.length)});str.push('<div style="float: left; width: '+divWidth+'px;"><b>Most watched:</b>');var mostWatched=[];for(var i=0;i<5&&i<epList.length;++i)str.push("<br />"+epKernel(epList[i],"viewCount"));str.push("</div>");str.push('<div style="float: left; width: '+
divWidth+'px;"><b>Least watched:</b>');var mostWatched=[];for(var i=epList.length-1;i>=epList.length-5&&i>=0;--i)str.push("<br />"+epKernel(epList[i],"viewCount"));str.push("</div>");epList.sort(function(a,b){return-((a.views.length?a.views[a.views.length-1]:0)-(b.views.length?b.views[b.views.length-1]:0))});str.push('<div style="float: left; width: '+divWidth+'px;"><b>Most recently watched:</b>');var mostWatched=[];for(var i=0;i<epList.length&&i<5;++i)str.push("<br />"+epKernel(epList[i],"mostRecent"));
str.push("</div>");epList.sort(function(a,b){return(a.views.length?a.views[0]:0)-(b.views.length?b.views[0]:0)});str.push('<div style="float: left; width: '+divWidth+'px;"><b>Least recently watched:</b>');var mostWatched=[];for(var i=0;i<epList.length&&i<5;++i)str.push("<br />"+epKernel(epList[i],"leastRecent"));str.push("</div>");$("#stats").html(str.join(""))},1);return'<div id="stats"></div>'+'<div id="calendar" style="clear: both;" class="calendar"></div>'}
function testMstViz(console){var value="Key: R - By (R)andom selection Q - By re(Q)uest T - By total viewing walk(T)hrough   1 - 2013.2.6...  MST3K 101 - 2013.2.6T1 102 - 2013.2.6T1 103 - 2013.2.7T1 104 - 2013.2.7T1 105 - 2013.2.8T1 106 - 2013.2.8T1 107 - 2013.2.11T1 108 - 2013.2.11T1 109 - 2013.2.11T1 110 - 2013.2.11T1 111 - 2013.2.12T1 112 - 2013.2.12T1 113 - 2013.2.12T1 201 - 2013.2.13T1 202 - 2013.2.13T1 203 - 2013.2.13T1 204 - 2013.2.14T1 205 - 2013.2.14T1 206 - 2013.2.15T1 207 - 2013.2.19T1, 2013.2.25Q 208 - 2013.2.19T1 209 - 2013.2.19T1 210 - 2013.2.20T1 211 - 2013.2.20T1 212 - 2013.2.22T1 213 - 2013.2.25T1 301 - 2013.2.22Q, 2013.2.27T 302 - 2013.2.27T1 303 - 2013.2.27T1 304 - 2013.2.27T1 305 - 2013.3.1T1 306 - 2013.3.1T1 307 - 2013.2.15R 308 - 309 - 310 - 311 - 312 - 313 - 314 - 315 - 316 - 317 - 2013.2.11R 318 - 319 - 320 - 321 - 322 - 323 - 324 - 401 - 402 - 403 - 404 - 405 - 406 - 407 - 408 - 409 - 410 - 411 - 412 - 413 - 414 - 415 - 416 - 417 - 418 - 419 - 420 - 421 - 2013.2.26R 422 - 423 - 424 - 501 - 502 - 503 - 504 - 505 - 506 - 507 - 508 - 509 - 510 - 511 - 512 - 513 - 514 - 515 - 516 - 517 - 518 - 519 - 520 - 521 - 522 - 523 - 524 - 601 - 602 - 603 - 2013.2.25R 604 - 605 - 606 - 2013.2.25R 607 - 608 - 609 - 610 - 611 - 612 - 2013.2.20Q 613 - 2013.2.12R 614 - 615 - 616 - 617 - 618 - 619 - 620 - 621 - 622 - 623 - 2013.2.4R 624 - TM - 701 - 702 - 703 - 704 - 705 - 706 - 707 - 801 - 802 - 803 - 804 - 805 - 806 - 807 - 808 - 809 - 810 - 811 - 812 - 813 - 814 - 815 - 816 - 817 - 818 - 819 - 820 - 821 - 822 - 901 - 902 - 903 - 904 - 905 - 906 - 907 - 908 - 909 - 910 - 911 - 912 - 913 - 2013.2.22R 1001 - 1002 - 1003 - 1004 - 1005 - 2013.2.13R 1006 - 1007 - 1008 - 1009 - 1010 - 1011 - 2013.2.15R 1012 - 1013 -  TFC KFS - 2013.2.19Q, 2013.2.20Q";
checkMstViz(value)}if(node)module.exports={test:function(console){testMstViz(console)}};"use strict";function getRand(n){if(n==null)n=32;var corpus="abcdefghjijklmnopqrstuvwxyzABCDEFGHJIJKLMNOPQRSTUVWXYZ0123456789",ret=[];for(var i=0;i<n;++i)ret.push(corpus.charAt(Math.floor(corpus.length*Math.random())));return ret.join("")}
var actuate=function(){var modules=getColorsModules().concat(getNumbersModules()).concat(getDefaultModules()).concat(getPlottingModules()).concat(getMst3kModules()).concat(getMst3kVizModules());modules.sort(function(a,b){return-(a.precedence-b.precedence)});return function(value){for(var i=0;i<modules.length;++i){var mod=modules[i],ret=mod.kernel(value);if(ret==null||ret===false)continue;else if(ret===true)break;else if(typeof ret=="string"){$("#results").html(ret);break}}}}();
function getDefaultModules(){return[{name:"HelpMenu",precedence:0,kernel:function(value){return value.match(/^\s*help\s*$/i)?helpContents:null}},{name:"Default",precedence:0,kernel:function(value){return value==""?"":"what is this I don't even"}}]}var helpContents;
$(document).ready(function(){helpContents=$("#results").html();function keyupCont(){$("#results").hide("fast",function(){actuate($("#twsc").val());$("#results").show("fast")})}var tz=jstz.determine();tz.name();var visible=true;$("#twsc").keyup(function(event){if(event&&event.which===13)if(visible){visible=false;var image=$("#image");if(image.length)image.slideUp("fast",function(){keyupCont()});else keyupCont()}else keyupCont()})});
